/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yoson_cache_CacheStorage */

#ifndef _Included_com_yoson_cache_CacheStorage
#define _Included_com_yoson_cache_CacheStorage
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_yoson_cache_CacheStorage
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;JIZ)Z
 */
JNIEXPORT jobject JNICALL Java_com_yoson_cache_CacheStorage_open
  (JNIEnv *, jobject, jstring, jstring, jlong, jint, jboolean);

/*
 * Class:     com_yoson_cache_CacheStorage
 * Method:    insert
 * Signature: ([BI[BIZI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yoson_cache_CacheStorage_insert
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jboolean, jint, jobject);

/*
 * Class:     com_yoson_cache_CacheStorage
 * Method:    delete
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yoson_cache_CacheStorage_delete
  (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     com_yoson_cache_CacheStorage
 * Method:    select
 * Signature: ([BI)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_com_yoson_cache_CacheStorage_select
  (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     com_yoson_cache_CacheStorage
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_yoson_cache_CacheStorage_close
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_yoson_cache_CacheStorage
 * Method:    destory
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_yoson_cache_CacheStorage_destory
  (JNIEnv *, jobject, jobject);


/*
 * Class:     com_yoson_cache_CacheStorage
 * Method:    getAllKey
 * Signature: (Ljava/nio/ByteBuffer;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_yoson_cache_CacheStorage_getAllKey
  (JNIEnv *, jobject, jobject);


/*
 * Class:     com_yoson_cache_CacheStorage
 * Method:    reMaxSize
 * Signature: (JLjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yoson_cache_CacheStorage_reMaxSize
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
